#!/bin/bash
function commit_folder() {
    folder=$1
    desc=$2
    if [ -d "$folder" ]; then
        echo "# $(basename "$folder")" > "$folder/README.md"
        echo "" >> "$folder/README.md"
        echo "$desc" >> "$folder/README.md"
        git add "$folder/README.md"
        git commit -m "$desc"
    fi
}
function commit_file() {
    file=$1
    desc=$2
    if [ -f "$file" ]; then
        echo " " >> "$file"
        git add "$file"
        git commit -m "$desc"
    fi
}
commit_folder "app" "Berisi logika utama aplikasi dan kontroler"
commit_folder "bootstrap" "Digunakan untuk memuat sistem awal framework"
commit_folder "config" "Menyimpan seluruh pengaturan dasar sistem"
commit_folder "database" "Menyimpan struktur tabel dan data bawaan"
commit_folder "docker" "Konfigurasi khusus untuk menjalankan aplikasi di Docker"
commit_folder "public" "File utama dan aset publik (gambar, CSS, JS) untuk browser"
commit_folder "resources" "Menyimpan tampilan antarmuka (views) dan aset mentah"
commit_folder "routes" "Tempat mengatur seluruh tautan URL (rute) aplikasi"
commit_folder "storage" "Menyimpan file hasil unggahan user dan log error internal"
commit_file ".dockerignore" "Daftar file yang diabaikan saat proses build Docker"
commit_file ".env.example" "Contoh konfigurasi variabel environment dasar"
commit_file ".gitignore" "Daftar file yang dilarang untuk diunggah ke GitHub"
commit_file "artisan" "Program bawaan Laravel untuk menjalankan perintah"
commit_file "composer.json" "Daftar pustaka PHP pihak ketiga yang digunakan"
commit_file "composer.lock" "Mengunci versi pustaka PHP agar stabil"
commit_file "docker-compose.yml" "Konfigurasi untuk menjalankan seluruh layanan Docker"
commit_file "package-lock.json" "Mengunci versi pustaka Javascript/Node.js"
commit_file "package.json" "Daftar pustaka Javascript pihak ketiga"
commit_file "vite.config.js" "Konfigurasi untuk kompilasi file aset CSS dan JS"
commit_file "README.md" "Dokumentasi utama yang berisi panduan proyek"
commit_folder "app/Http" "Berisi Controller dan Middleware untuk menangani permintaan web"
commit_folder "app/Http/Controllers" "Berisi Controller untuk menangani logika alur aplikasi"
commit_folder "app/Http/Middleware" "Berisi Middleware untuk mencegat dan memfilter akses pengguna"
commit_folder "app/Http/Requests" "Berisi logika validasi formulir tingkat lanjut"
commit_folder "app/Services" "Berisi layanan logika pihak ketiga seperti integrasi Supabase"
commit_folder "app/Providers" "Berisi pendaftaran dan konfigurasi layanan inti aplikasi"
commit_folder "app/Policies" "Berisi aturan hak akses (otorisasi) tingkat lanjut"
commit_folder "app/Mail" "Berisi pengaturan dan kelas format pengiriman email"
commit_folder "resources/views" "Berisi seluruh tampilan halaman web (Blade templates)"
commit_folder "resources/css" "Berisi file kode desain tampilan CSS mentah"
commit_folder "resources/js" "Berisi file kode interaktivitas Javascript mentah"
commit_folder "resources/views/departments" "Tampilan halaman manajemen departemen"
commit_folder "resources/views/layouts" "Kerangka dasar struktur tampilan halaman utama (template)"
commit_folder "resources/views/components" "Komponen tampilan (UI) yang dapat digunakan berulang"
commit_folder "resources/views/emails" "Format tampilan (template) untuk pengiriman email"
commit_folder "resources/views/leave-types" "Tampilan halaman pengaturan tipe cuti"
commit_folder "resources/views/dashboard" "Tampilan halaman beranda utama (dashboard)"
commit_folder "resources/views/reports" "Tampilan halaman laporan dan statistik"
commit_folder "resources/views/leave" "Tampilan halaman manajemen pengajuan cuti"
commit_folder "resources/views/auth" "Tampilan halaman login, pendaftaran, dan autentikasi"
commit_folder "resources/views/notifications" "Tampilan komponen notifikasi peringatan"
commit_folder "resources/views/profile" "Tampilan halaman profil pengguna pribadi"
commit_folder "resources/views/activity-logs" "Tampilan halaman riwayat aktivitas sistem"
commit_folder "resources/views/users" "Tampilan halaman manajemen seluruh pengguna (karyawan)"
commit_folder "resources/views/settings" "Tampilan halaman pengaturan aplikasi"
commit_folder "database/migrations" "Berisi skrip untuk membuat dan mengubah tabel database"
commit_folder "database/seeders" "Berisi skrip untuk mengisi data awal ke dalam tabel"
commit_folder "public/build" "Berisi aset otomatis hasil kompilasi dari Vite"
commit_folder "public/css" "Berisi file CSS statis yang dapat diakses publik"
commit_folder "public/js" "Berisi file JS statis yang dapat diakses publik"
commit_folder "public/images" "Berisi gambar statis pendukung tampilan aplikasi"
commit_folder "public/build/assets" "Kumpulan file aset gaya dan skrip yang sudah dikompilasi"
commit_folder "storage/app" "Tempat penyimpanan file khusus aplikasi (internal)"
commit_folder "storage/app/private" "Penyimpanan file rahasia yang tidak dapat diakses publik"
commit_folder "storage/app/public" "Penyimpanan file unggahan yang dapat diakses oleh publik"
commit_folder "storage/logs" "Tempat penyimpanan catatan (log) peringatan dan error sistem"
commit_folder "storage/framework" "Penyimpanan cache internal yang digunakan oleh sistem framework"
commit_folder "storage/framework/views" "Cache tampilan halaman web yang sudah dikompilasi (otomatis)"
commit_folder "storage/framework/testing" "Tempat penyimpanan data sementara untuk pengujian aplikasi"
commit_folder "storage/framework/sessions" "Penyimpanan data informasi sesi login pengguna"
commit_folder "storage/framework/cache" "Penyimpanan data sementara (cache) agar aplikasi berjalan cepat"
commit_folder "bootstrap/cache" "File cache inti untuk mempercepat proses memuat aplikasi"
commit_folder "docker/php" "Konfigurasi khusus untuk layanan server PHP pada Docker"
commit_folder "docker/nginx" "Konfigurasi khusus untuk layanan web server NGINX pada Docker"
